# Generated by Django 4.2.7 on 2023-11-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('players', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
