# Generated by Django 4.2.7 on 2023-11-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='creator',
            field=models.CharField(default='Default', max_length=200, verbose_name='Creator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
